server {
    listen 80;
    server_name localhost;

    port_in_redirect off;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Check if the requested file ($uri) or directory ($uri/) physically exists on disk.
        # If it doesn't exist, issue a 302 redirect back to /
        try_files $uri $uri/ @redirect;
    }

    location @redirect {
        return 302 /;
    }
}